import { LightningElement } from 'lwc';

export default class Atividade1 extends LightningElement {
    pessoa = [
        {
        id: 989898,
        primeironome:          "BONNIE" , 
        sobrenome:              "CLYDE", 
        idade:                  "32", 
        email:                  "bn@yahoo.com", 
        classificacao:          "hot" , 
        empresa:                "Salesforce" , 
        receitaanual:           10000000000}, 
        ];
}
